### PR TITLE
Add travis configuration

### PR DESCRIPTION
**Pull request by moorscode**

### CODE REVIEW

**Comment by jrfnl** [comment]
@moorscode FYI: my request was purely for turning it on, I already have a script ready in the wings.

**Comment by moorscode** [comment]
I have upgraded most scripts to be better usable, using multiline conditionals and folding of specific parts when they succeed.
Would be a waste not to implement here as well :)

**Comment by jrfnl** [comment]
Ok, no worries, I'll just update your script with my additional changes in a future pull.

**Comment by moorscode** [comment]
PHPCS is failing on the build, but merging regardless as this will be fixed in future pulls.
Will enable requiring a build passing before merge is allowed, after we had a successful pass.

**Comment by jrfnl** [comment]
Or just leave out the PHPCS check for now - I will add it back in when the config has been updated ;-)

**Pull request merged**
